[database]#regular database
kraken2=/staging/fanyucai/virus/ref/kraken2/
host=/staging/fanyucai/virus/ref/host/human
nextclade_db=/staging/fanyucai/virus/ref/nextclade_db/
vsp=/staging/fanyucai/virus/ref/VSP/

[blast_db]#blast database=/path/+blast_db_name
nt_viruses=/staging/fanyucai/virus/ref/nt_viruses/nt_viruses

[fasta]
virus=/staging/fanyucai/virus/ref/NCBI_Nucleotide_Completeness/virus_completeness_unique.fasta

[parameter]
#only choices:500,1000,1500
contig_min_length=1000
identify=0.95