[database]
kraken2=/staging/fanyucai/virus/ref/kraken2/
host=/staging/fanyucai/virus/ref/host/human
virus=/staging/fanyucai/virus/ref/NCBI_Nucleotide_Completeness/virus_completeness_unique.fasta
nextclade_db=/staging/fanyucai/virus/ref/nextclade_db/

#attention:nt_viruses =/path/+blast_db_name
nt_viruses=/staging/fanyucai/virus/ref/nt_viruses/nt_viruses
#attention:vsp =/path/+blast_db_name
vsp=/staging/fanyucai/virus/ref/VSP/VSP

[fasta]
vsp=/staging/fanyucai/virus/ref/VSP/VSP.fasta

[parameter]
contig_min_length=1000
identify=0.95

[bowtie2]
bowtie2=/staging/fanyucai/virus/ref/bowtie2/