[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name="virus"
description ="Virus NGS bioinformatics pipeline."
version = "1.0"
requires-python = ">=3"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
]
authors = [
    { name="fanyucai", email="fanyucai3@gamil.com" },
]